const src = {
    banners:[
        {banner_src:"/view/imgs/desktop-454.jpg"},
        {banner_src:"/view/imgs/desktop-457.jpg"},
        {banner_src:"/view/imgs/desktop-458.jpg"},
        {banner_src:"/view/imgs/desktop-460.jpg"},
    ],
    movies:[
        {movie_src:"/view/movies/a-familia-addams-2-pe-na-estrada.jpg"},
        {movie_src:"/view/movies/a-mensageira.jpg"},
        {movie_src:"/view/movies/de-volta-a-italia.jpg"},
        {movie_src:"/view/movies/espiritos-obscuros.jpg"},
        {movie_src:"/view/movies/eternos.jpg"},
        {movie_src:"/view/movies/la-vamos-nos-.jpg"},
        {movie_src:"/view/movies/marighella.jpg"},
        {movie_src:"/view/movies/uma-historia-de-familia.jpg"},
        {movie_src:"/view/movies/yalda-uma-noite-de-perdao.jpg"},
    ],
    infos:[
        {infos_src:"/view/infos/cinescola-mob.gif"},
        {infos_src:"/view/infos/festa-no-cinema-mob.gif"},
    ]
}
